version: "3"
services:
  dev-db:
    container_name: dev-db
    image: gvenzl/oracle-free:23-slim-faststart
    volumes:
      - ./db:/container-entrypoint-startdb.d
    environment:
      ORACLE_DATABASE: devdb
      ORACLE_PASSWORD: password
      APP_USER: username
      APP_USER_PASSWORD: password
    ports:
      - 1521:1521
