services:
  dev-db:
    container_name: dev-db
    image: container-registry-mumbai.oracle.com/database/free
    volumes:
      - ./init-scripts:/opt/oracle/scripts/startup
    environment:
      ORACLE_PWD: password
    ports:
      - 1521:1521
