name: oracle-simple tests
on:
  push:
    branches:
      - master
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v5
     - uses: cachix/install-nix-action@v31
       with:
         nix_path: nixpkgs=channel:nixos-unstable
     - name: nixpkgs update
       run: nix-channel --update
     - name: run oracle
       run: nix-shell -p docker-compose --run "docker-compose up -d"
     - name: build
       run: nix-build
     - name: test
       run: ./result/bin/tests
